# Generated by Django 5.2.4 on 2025-08-11 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdsBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("sponsor", "Sponsor"),
                            ("event", "Event"),
                            ("announcement", "Announcement"),
                            ("club", "Club"),
                        ],
                        default="sponsor",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="banners/"),
                ),
                ("url", models.URLField(blank=True)),
                ("sponsor", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Higher number means higher priority"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Advertisement Banner",
                "verbose_name_plural": "Advertisement Banners",
                "ordering": ["-priority", "-start_date"],
            },
        ),
    ]
