# Generated by Django 5.2.4 on 2025-08-16 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_adsbanner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("canteen", "Canteen"),
                            ("cafe", "Cafe"),
                            ("bookstore", "Bookstore"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "coin_cost",
                    models.PositiveIntegerField(help_text="Number of coins required"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monetary value of voucher",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["coin_cost"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="reward_coins",
            field=models.PositiveIntegerField(default=0, help_text="Reward in coins"),
        ),
        migrations.CreateModel(
            name="CoinTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("earned", "Earned"), ("spent", "Spent")],
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RewardCoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coins",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of reward coins"
                    ),
                ),
                (
                    "total_earned",
                    models.PositiveIntegerField(
                        default=0, help_text="Total coins earned"
                    ),
                ),
                (
                    "total_spent",
                    models.PositiveIntegerField(
                        default=0, help_text="Total coins spent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_coins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoucherRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.voucher"
                    ),
                ),
            ],
            options={
                "ordering": ["-redeemed_at"],
            },
        ),
    ]
