# Generated by Django 5.2.4 on 2025-08-17 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_voucher_item_reward_coins_cointransaction_rewardcoin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Location", "verbose_name_plural": "Locations"},
        ),
        migrations.RemoveField(
            model_name="location",
            name="building",
        ),
        migrations.RemoveField(
            model_name="location",
            name="floor",
        ),
        migrations.RemoveField(
            model_name="location",
            name="name",
        ),
        migrations.RemoveField(
            model_name="location",
            name="room",
        ),
        migrations.AddField(
            model_name="item",
            name="admin_notes",
            field=models.TextField(blank=True, help_text="Admin notes about the item"),
        ),
        migrations.AddField(
            model_name="item",
            name="admin_verified",
            field=models.BooleanField(
                default=False, help_text="Item verified by admin in person"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="admin_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="admin_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="claimed_from_admin",
            field=models.BooleanField(
                default=False, help_text="Item claimed from admin section"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="claimed_from_admin_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="claimer_id_verified",
            field=models.BooleanField(
                default=False, help_text="Claimer's ID verified by admin"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="claimer_name",
            field=models.CharField(
                blank=True, help_text="Name of person claiming the item", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="dropped_at_admin",
            field=models.BooleanField(
                default=False, help_text="Item physically dropped at admin section"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="dropped_at_admin_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="floor_area",
            field=models.CharField(
                choices=[
                    ("library", "Library"),
                    ("it_lab", "IT Lab"),
                    ("kafe_kodes", "Kafe Kodes"),
                    ("bathroom", "Bathroom"),
                    ("admin_section", "Admin Section"),
                    ("academic_support", "Academic Support"),
                    ("found_items_drop", "Found Items Drop-off"),
                    ("items_claim", "Items Claim Center"),
                    ("class_201", "Class 201"),
                    ("class_202", "Class 202"),
                    ("class_203", "Class 203"),
                    ("class_204", "Class 204"),
                    ("class_301", "Class 301"),
                    ("class_302", "Class 302"),
                    ("class_303", "Class 303"),
                    ("class_304", "Class 304"),
                    ("class_401", "Class 401"),
                    ("class_402", "Class 402"),
                    ("class_403", "Class 403"),
                    ("class_404", "Class 404"),
                    ("class_501", "Class 501"),
                    ("class_502", "Class 502"),
                    ("class_503", "Class 503"),
                    ("class_504", "Class 504"),
                    ("program_hall", "Program Hall"),
                    ("dolab", "DoLab"),
                    ("cipl", "CIPL"),
                    ("table_tennis", "Table Tennis Board"),
                    ("canteen", "Canteen"),
                    ("tech_club", "Tech Club"),
                    ("finance_club", "Finance Club"),
                    ("social_club", "Social Club"),
                    ("athletics_club", "Athletics Club"),
                    ("literature_club", "Literature Club"),
                    ("skillbee_club", "SkillBee Club"),
                    ("other", "Other Location"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("parking", "Parking Space"),
                    ("ground_floor", "Ground Floor"),
                    ("first_floor", "First Floor"),
                    ("second_floor", "Second Floor"),
                    ("third_floor", "Third Floor"),
                    ("fourth_floor", "Fourth Floor"),
                    ("fifth_floor", "Fifth Floor"),
                    ("sixth_floor", "Sixth Floor"),
                    ("seventh_floor", "Seventh Floor"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="specific_location",
            field=models.CharField(
                blank=True,
                help_text="Specific details like 'near entrance', 'back corner', etc.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("claimed", "Claimed"),
                    ("expired", "Expired"),
                    ("closed", "Closed"),
                    ("pending_verification", "Pending Admin Verification"),
                    ("verified", "Admin Verified"),
                    ("dropped_off", "Dropped at Admin Section"),
                    ("ready_for_claim", "Ready for Claim at Admin Section"),
                ],
                default="active",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="AdminOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("verify", "Verify Item"),
                            ("drop_off", "Mark as Dropped Off"),
                            ("claim", "Process Claim"),
                            ("update_status", "Update Status"),
                            ("add_note", "Add Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("operation_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("previous_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(blank=True, max_length=20)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_operations",
                        to="core.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Operation",
                "verbose_name_plural": "Admin Operations",
                "ordering": ["-operation_date"],
            },
        ),
    ]
