# Generated by Django 5.2.4 on 2025-08-17 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_location_options_remove_location_building_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("item_found", "Item Found"),
                            ("item_claimed", "Item Claimed"),
                            ("item_verified", "Item Admin Verified"),
                            ("item_dropped_off", "Item Dropped at Admin"),
                            ("item_ready_claim", "Item Ready for Claim"),
                            ("admin_action", "Admin Action Required"),
                            ("system_alert", "System Alert"),
                            ("reward_earned", "Reward Earned"),
                            ("contact_received", "New Contact Message"),
                        ],
                        max_length=25,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "html_template",
                    models.TextField(help_text="HTML email template with placeholders"),
                ),
                (
                    "text_template",
                    models.TextField(
                        help_text="Plain text email template with placeholders"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["template_type"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("item_found", "Item Found"),
                            ("item_claimed", "Item Claimed"),
                            ("item_verified", "Item Admin Verified"),
                            ("item_dropped_off", "Item Dropped at Admin"),
                            ("item_ready_claim", "Item Ready for Claim"),
                            ("admin_action", "Admin Action Required"),
                            ("system_alert", "System Alert"),
                            ("reward_earned", "Reward Earned"),
                            ("contact_received", "New Contact Message"),
                        ],
                        max_length=25,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "is_admin_notification",
                    models.BooleanField(
                        default=False,
                        help_text="If True, all admins will receive this notification",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, help_text="Email sent successfully"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.adminoperation",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.item",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
